'use client'
import './globals.css'
import { SessionProvider } from 'next-auth/react';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <SessionProvider>
        <>{children}</>
      </SessionProvider>
      </body>
    </html>
  )
}
